In [2]:
from files.properties import Properties
from utils.fiber import Fiber

from operator import itemgetter
import numpy as np

In [3]:
f = Fiber(Properties())

C:\Users\gusta\Desktop\simroel-py-v3\data\parameters.json


In [4]:
f.fiber_data.keys()

dict_keys([(1, 2), (2, 1), (2, 3), (3, 2), (3, 4), (4, 3), (4, 1), (1, 4)])

In [5]:
#f.fiber_data.get((1, 2))

In [6]:
route = [(1, 2), (2, 3)]
core = 2
slots = (0, 10)
gb = 1

In [7]:
route_data = np.stack(itemgetter(*route)(f.fiber_data))
route_data.shape

(2, 7, 100)

In [8]:
# for pair in route:
#     f.fiber_data.get(pair)[core, slots[0]:slots[1]] = 0
#     f.fiber_data.get(pair)[core, slots[1]-1] = -2

In [17]:
def first_fit(fiber, conn, route, core):
    slot_size = int(conn["slots"])
    guard_band = int(conn["gb"])
    
    sample = np.stack(itemgetter(*route)(f.fiber_data))
    print(sample.shape)
    print(sample)
    
    for slot in range(sample.shape[-1] - 1 - slot_size+guard_band):
        if np.all((sample[:, core, slot:slot+slot_size+guard_band]) == -1):
            return slot, slot+slot_size+guard_band 
    

def random_fit(fiber, conn, route, core):
    slot_size = int(conn["slots"])
    guard_band = int(conn["gb"])
    fiber_slots = []
    
    sample = np.stack(itemgetter(*route)(f.fiber_data))
    print(sample.shape)
    print(sample)
    
    for slot in range(sample.shape[-1] - 1 - slot_size + guard_band):
        if np.all((sample[:, core, slot:slot + slot_size + guard_band]) == -1):
            fiber_slots.append((slot, slot + slot_size + guard_band))

    if len(fiber_slots) == 0: return -1
    np.random.shuffle(fiber_slots)
    return fiber_slots[0]

def alloc(fiber, conn, route, core, how="first_fit"):
    slots = globals()[how](fiber.get(*route), conn, route, core)
    print(slots)

In [15]:
route

[(1, 2), (2, 3)]

In [14]:
f.fiber_data.get(*route).shape

(7, 100)

In [11]:
route

[(1, 2), (2, 3)]

In [34]:
np.expand_dims(f.fiber_data.get((1, 4)), axis=0)[:, 0, :5]

array([[-1, -1, -1, -1, -1]], dtype=int8)

In [20]:
conn = {"slots": 5, "gb":1}
alloc(f.fiber_data, conn, [(1, 4)], core)

(7, 100)
[[-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
  -1 -1 -1 -1]
 [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1

IndexError: too many indices for array: array is 2-dimensional, but 3 were indexed

In [19]:
conn = {"slots": 5, "gb":1}
alloc(f.fiber_data, conn, route, core, how="random_fit")

(2, 7, 100)
[[[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]

 [[-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  ...
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]
  [-1 -1 -1 ... -1 -1 -1]]]
(63, 69)


In [79]:
conn = {"slots": 5, "gb":1}
alloc(f.fiber_data, conn, route, core)

(0, 6)


In [94]:
conn = {"slots": 5, "gb":1}
alloc(f.fiber_data, conn, route, core, how="random_fit")

(61, 67)
